/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:49: UserWarning: Checkpoint directory /content/gdrive/My Drive/PUSHMI/saved_models/distance_100_5e-05_0.0 exists and is not empty.
  warnings.warn(*args, **kwargs)
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:49: UserWarning: Checkpoint directory /content/gdrive/My Drive/PUSHMI/saved_models/distance_100_5e-05_0.0 exists and is not empty.
  warnings.warn(*args, **kwargs)
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:49: UserWarning: Checkpoint directory /content/gdrive/My Drive/PUSHMI/saved_models/distance_100_5e-05_0.0 exists and is not empty.
  warnings.warn(*args, **kwargs)
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name       | Type       | Params
------------------------------------------
0 | activation | LeakyReLU  | 0     
1 | layer1     | Sequential | 640   
2 | layer2     | Sequential | 73.9 K
3 | layer3     | Sequential | 295 K 
4 | layer4     | Sequential | 1.2 M 
5 | fc1        | Linear     | 262 K 
6 | fc2        | Linear     | 5.1 K 
------------------------------------------
1.8 M     Trainable params
0         Non-trainable params
1.8 M     Total params
/usr/local/lib/python3.6/dist-packages/torchvision/transforms/functional_tensor.py:876: UserWarning: Argument fill/fillcolor is not supported for Tensor input. Fill value is zero
  warnings.warn("Argument fill/fillcolor is not supported for Tensor input. Fill value is zero")
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:49: UserWarning: Trying to log at a previous step. Use `commit=False` when logging metrics manually.
  warnings.warn(*args, **kwargs)
[34m[1mwandb[0m: [33mWARNING[0m Step must only increase in log calls.  Step 49 < 5000; dropping {'train_loss': 0.00029239983996376395, 'train_loss1': 0.005601587239652872, 'train_loss2': 0.005653384607285261, 'train_loss3': 0.000344197207596153}.
[34m[1mwandb[0m: [33mWARNING[0m Step must only increase in log calls.  Step 99 < 10000; dropping {'train_loss': -0.0022551734000444412, 'train_loss1': 0.0007589285960420966, 'train_loss2': 0.003842263715341687, 'train_loss3': 0.000828161952085793}.
[34m[1mwandb[0m: [33mWARNING[0m Step must only increase in log calls.  Step 149 < 15000; dropping {'train_loss': -0.016049329191446304, 'train_loss1': 0.0022905003279447556, 'train_loss2': 0.023311471566557884, 'train_loss3': 0.004971642512828112}.
[34m[1mwandb[0m: [33mWARNING[0m Step must only increase in log calls.  Step 199 < 20000; dropping {'train_loss': -0.05567334592342377, 'train_loss1': 0.019376035779714584, 'train_loss2': 0.11012319475412369, 'train_loss3': 0.035073816776275635}.
[34m[1mwandb[0m: [33mWARNING[0m Step must only increase in log calls.  Step 249 < 25000; dropping {'train_loss': -0.07484540343284607, 'train_loss1': 0.03985798731446266, 'train_loss2': 0.26522737741470337, 'train_loss3': 0.15052399039268494}.
[34m[1mwandb[0m: [33mWARNING[0m Step must only increase in log calls.  Step 299 < 30000; dropping {'train_loss': -0.20660340785980225, 'train_loss1': 0.06081251800060272, 'train_loss2': 0.3538874387741089, 'train_loss3': 0.08647150546312332}.
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:49: UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...
  warnings.warn(*args, **kwargs)
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:49: UserWarning: Checkpoint directory /content/gdrive/My Drive/PUSHMI/saved_models/distance_100_5e-05_0.0 exists and is not empty.
  warnings.warn(*args, **kwargs)
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name       | Type       | Params
------------------------------------------
0 | activation | LeakyReLU  | 0     
1 | layer1     | Sequential | 640   
2 | layer2     | Sequential | 73.9 K
3 | layer3     | Sequential | 295 K 
4 | layer4     | Sequential | 1.2 M 
5 | fc1        | Linear     | 262 K 
6 | fc2        | Linear     | 5.1 K 
------------------------------------------
1.8 M     Trainable params
0         Non-trainable params
1.8 M     Total params
/usr/local/lib/python3.6/dist-packages/torchvision/transforms/functional_tensor.py:876: UserWarning: Argument fill/fillcolor is not supported for Tensor input. Fill value is zero
  warnings.warn("Argument fill/fillcolor is not supported for Tensor input. Fill value is zero")
Epoch 0, global step 549: val_loss reached -0.21509 (best -0.21509), saving model to "/content/gdrive/My Drive/PUSHMI/saved_models/distance_100_5e-05_0.0/model-v1.ckpt" as top 1
Epoch 1, global step 1099: val_loss reached -0.26643 (best -0.26643), saving model to "/content/gdrive/My Drive/PUSHMI/saved_models/distance_100_5e-05_0.0/model-v1.ckpt" as top 1
Epoch 2, global step 1649: val_loss reached -0.32894 (best -0.32894), saving model to "/content/gdrive/My Drive/PUSHMI/saved_models/distance_100_5e-05_0.0/model-v1.ckpt" as top 1
Epoch 3, global step 2199: val_loss reached -0.33535 (best -0.33535), saving model to "/content/gdrive/My Drive/PUSHMI/saved_models/distance_100_5e-05_0.0/model-v1.ckpt" as top 1
Epoch 4, global step 2749: val_loss reached -0.36254 (best -0.36254), saving model to "/content/gdrive/My Drive/PUSHMI/saved_models/distance_100_5e-05_0.0/model-v1.ckpt" as top 1
Epoch 5, step 3299: val_loss was not in top 1
Epoch 6, step 3849: val_loss was not in top 1
Epoch 7, step 4399: val_loss was not in top 1
Epoch 8, step 4949: val_loss was not in top 1
Epoch 9, global step 5499: val_loss reached -0.38346 (best -0.38346), saving model to "/content/gdrive/My Drive/PUSHMI/saved_models/distance_100_5e-05_0.0/model-v1.ckpt" as top 1
Epoch 10, global step 6049: val_loss reached -0.39343 (best -0.39343), saving model to "/content/gdrive/My Drive/PUSHMI/saved_models/distance_100_5e-05_0.0/model-v1.ckpt" as top 1
Epoch 11, step 6599: val_loss was not in top 1
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:49: UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...
  warnings.warn(*args, **kwargs)
Epoch 12, step 6960: val_loss was not in top 1

